### ISSUE TITLE
请问PHP代码的第二行需要怎么配置才能用呢？

### ISSUE THREAD

**Issue by lvlinkeji** [jshensh/phpReverseProxy#2]
您好！请问PHP代码的第二行需要怎么配置才能用呢？

require('./vendor/autoload.php');

直接使用的话会报错。

Warning: require(./vendor/autoload.php): failed to open stream: No such file or directory

Fatal error: require(): Failed opening required './vendor/autoload.php' (include_path='.:')

使用环境是 nginx + php 7.4

**Comment by jshensh** [comment]
`composer require jshensh/php-curl-class`
