### ISSUE TITLE
建议添加浏览器UA跟随和header覆写功能

### ISSUE THREAD

**Issue by dreamren** [jshensh/phpReverseProxy#4]
工具非常好用！感谢！
经过测试，真实服务器收到的浏览器UA为：
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
而不是客户端UA，容易被针对风控。
另外希望可以加入请求头header覆盖功能用于指定Cookie、Token等。
也建议考虑将配置文件从代码中独立出来。感谢

**Comment by jshensh** [comment]
> 工具非常好用！感谢！ 经过测试，真实服务器收到的浏览器UA为： Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36 而不是客户端UA，容易被针对风控。 另外希望可以加入请求头header覆盖功能用于指定Cookie、Token等。 也建议考虑将配置文件从代码中独立出来。感谢

您好，自定义 Header 功能可以参考这边 https://github.com/jshensh/php-curl-class#header 实现
